travis:
  secure:
    BINSTAR_TOKEN: dzFV3o/7IDjoNqV3XQ1KfwCR2FRZjeK9V7b1yY3vz6nq2g+M8IwRKtVTuz7wkuMA2D1H24r74HEeNYFOTwcwGFtAK+C5ep5DgOwo5OEIKqZhOXiLUrKKSp4XtoHKcsiEju/Hmpvb0W4Bze0XqbXzDEYjXc1K5hSI8ZqoDQ4nXPhhVmZwnKca4vFhHGFBt5++ZtVxib/ngD1aAA/NynSJzDb6Jkuo6r+19mStCt5MRoJ1xZtInVnKANMr+yjHgbLg5zG5O9MvdvmBTh1WmP596o3EfNK25fY1D70kKOf3U9Y88ocKrCrSkl/rqpUa86OQhSS2BfGdf10INxFVE8BQn8YwDlVYk+oiw60TkfcbjdhCp8PYPOiTpAjEj8SDaHWKsWcIovpDdxmrnUiQeu0efRJfhYTDjHoc/r8OKxFzq3GSZeIRjY3KjOd715+AMY4WViQ4QlxVVxtqH4dx1YnR9L213KdKI1HJCVfdalzt/34QCIgJsz9GNUSmXmUIIXzmMViIWf+2wazjglSrdQbOXCiMAu1UYKy05XrybEYY65fBNqzzSXcXUOPn62iarvPQMIIbiIwmx0/wz8/9Vobc++4XhgvGw1g8ZT/EL7c5xzNEygsFZ6FKgCHAKbcGpZAvH4UtXvRQWRHKpkHQ4ixlH7xXzCzVP/JW7yjvurhX860=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
